apiVersion: v1
name: user-management-service
description: A Helm chart for User Management Service
type: application
version: 0.1.0
appVersion: 1.0.0
home: https://github.com/openrewrite-assist-testing-dataset/user-management-service
sources:
  - https://github.com/openrewrite-assist-testing-dataset/user-management-service
maintainers:
  - name: Development Team
    email: dev@example.com